### ISSUE TITLE
error to record page 256 (0x100)

### ISSUE THREAD

**Issue by Danielzar** [LowPowerLab/SPIFlash#21]
when recording page 256 (0x100)repeat recording page 0 (0x01) and when recording page 257 (0x101) repeat recording page 1(0x01) ..... etc
does not read correctly page 256(0x100) or higher
the above using TestFlash example

**Comment by LowPowerLab** [comment]
What TestFlash example are you talking about?

**Comment by Danielzar** [comment]
the TestFlash example it is in the library
SPIMemory-1.2.1/examples/TestFlash/TestFlash.ino
