### ISSUE TITLE
JEDEC ID is 3 bytes

### ISSUE THREAD

**Issue by ianccole** [LowPowerLab/SPIFlash#23]
I think the JEDEC ID is 3 bytes: 

https://www.winbond.com/resource-files/w25x40cl_e01.pdf

1: Manufacturer Id
2: Memory type
3: Capacity type

This:
```
  uint32_t jedecid = 0;
  jedecid |= (uint32_t)SPI.transfer(0) << 16;
  jedecid |= SPI.transfer(0) << 8;
  jedecid |= SPI.transfer(0);
```
yields EF3013 and EF4016 on 2 boards I have

**Comment by LowPowerLab** [comment]
True, but in the case of the chips I use I only care to ensure the instruction set will work, not so much about capacity. That means checking the manufacturer and mem type.

**Comment by ianccole** [comment]
Ok. Fair enough. I’ll close this issue.
