### ISSUE TITLE
Arduino 1.6

### ISSUE THREAD

**Issue by kalanda** [LowPowerLab/SPIFlash#8]
This library works perfectly fine on Arduino 1.0.6 but inside the new release 1.6.0 the sketch hangs very soon. Is easy to check using the SPIFlash_ReadWrite example. I think this issue is because of changes on SPI.h library but didn't found any solution.

**Comment by tbowmo** [comment]
I see the exact same thing here, after upgrade to arduino 1.6.0, SPIFlash_ReadWrite is crashing..

**Comment by kalanda** [comment]
Maybe this fork's commit has solved it but I don't see any pull request to this repo:
https://github.com/TomWS1/SPIFlash/commit/8c32a312ea52d703bafbe2856222f4847491a513

**Comment by vicatcu** [comment]
fwiw, seems like this could be Moteino specific, my fork for WildFire seems to still be working fine in arduino 1.6.0

**Comment by tbowmo** [comment]
@kalanda tried the one from @TomWS1 repo, it can initialize the SPI flash library successfully

**Comment by kalanda** [comment]
There is a pull request https://github.com/LowPowerLab/SPIFlash/pull/9 for @LowPowerLab from @TomWS1 waiting for revision.
